export const FETCH_USERS_START = 'FETCH_USERS_START'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USER_DELETE = 'FETCH_USER_DELETE'
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL'
